Beginning Vectorization
complete vectorization using te standard gymnasium API but the required one is from SB3 so stuff should be rewritten.

Possibly initialization is correct, still to do step and reset + below function are still abstract

TypeError: Can't instantiate abstract class PusherDreamEnv with abstract methods env_is_wrapped, env_method, get_attr, set_attr, step_async, step_wait